export const CREATE_BLOG = 'CREATE_BLOG';     
export const CREATE_BLOG_SUCCESS = 'CREATE_BLOG_SUCCESS';
export const UPDATE_BLOG=  'UPDATE_BLOG';
export const UPDATE_BLOG_SUCCESS = 'UPDATE_BLOG_SUCCESS';
export const FETCH_BLOGS= 'FETCH_BLOGS';   
export const FETCH_BLOGS_SUCCESS = 'FETCH_BLOGS_SUCCESS';
export const FETCH_BLOG = 'FETCH_BLOG';
export const FETCH_BLOG_SUCCESS = 'FETCH_BLOG_SUCCESS';
export const DELETE_BLOG = 'DELETE_BLOG';
export const DELETE_BLOG_SUCCESS = 'DELETE_BLOG_SUCCESS';
export const BLOG_ERROR= 'BLOG_ERROR'; 

